### PR TITLE
chore: enable laravel 9 support

### PR DESCRIPTION
**Pull request by benswinburne**
## Description

Enables installation in Laravel 9

## Motivation and context

The composer requirements in the package prevent installation in a Laravel 9 project. This PR enables it.

## How has this been tested?

Enabled Laravel 9 with PHP 8.0.2 (https://laravel.com/docs/9.x/upgrade#updating-dependencies) in travis to run test suite.

Edit: travis is no longer running. Wrote a PR for github actions which when merged can be used to test this against PHP 8 and Laravel 9

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Go over all the following points, and put an `x` in all the boxes that apply.

Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our [continuous integration](http://www.phptherightway.com/#continuous-integration) server to make sure your [tests and code style pass](https://help.github.com/articles/about-required-status-checks/).

- [x] I have read the **[CONTRIBUTING](CONTRIBUTING.md)** document.
- [x] My pull request addresses exactly one patch/feature.
- [x] I have created a branch for this patch/feature.
- [x] Each individual commit in the pull request is meaningful.
- [x] I have added tests to cover my changes.
- [x] If my change requires a change to the documentation, I have updated it accordingly.

If you're unsure about any of these, don't hesitate to ask. We're here to help!

### CODE REVIEW

**Review by anfischer — APPROVED** [review]

**Comment by anfischer** [comment]
Hi Ben

Sorry for my late reply.

Do you have time to solve the conflict in `.travis.yml`? Then I will merge as soon as possible afterwards.

**Comment by benswinburne** [comment]
> Hi Ben
> 
> Sorry for my late reply.
> 
> Do you have time to solve the conflict in `.travis.yml`? Then I will merge as soon as possible afterwards.

@anfischer

- I've resolved the conflict by removing the travis config as it's no longer used
- I added Laravel 9 to the GH actions (as it wasn't present in the GH actions PR yet)
- I also replaced the travis badge with the GH on which I missed in the other PR - not technically related to this PR but seemed so trivial to need to create another one for

**Review by anfischer — APPROVED** [review]

**Comment by anfischer** [comment]
Perfect, I merged the PR. 

Thanks for your contribution.

**Comment by benswinburne** [comment]
@anfischer thanks for merging. I made a mistake with the URL of the badge in the readme. Any chance you can push a change to save a PR

It should be

```
https://img.shields.io/github/workflow/status/anfischer/cloner/Main%20workflow?style=flat-square
```

**Comment by anfischer** [comment]
> @anfischer thanks for merging. I made a mistake with the URL of the badge in the readme. Any chance you can push a change to save a PR
> 
> It should be
> 
> ```
> https://img.shields.io/github/workflow/status/anfischer/cloner/Main%20workflow?style=flat-square
> ```

I have corrected it, thanks!

**Pull request merged**
