### PR TITLE
chore!: updated Laravel support to 8.x

### PR DESCRIPTION
**Pull request by benswinburne**
## Description

Updated the dependency of illuminate/support to work with the (at the time) current version, ^8.11.2.

Described Cloner version 1.0 in new readme but you may want to pick a new < 1.0 release number given you've not hit 1.0 yet so it doesn't need to be a major for a breaking change technically. 0.2?

On a side note and slightly related to these changes- now that there's a newer version of illumiminate/support with null checks in wraps, should this PR remove the NullWrapper too?

## Motivation and context

Why is this change required? What problem does it solve?

Allows installations on Laravel 8.

On an (admittedly) L7 installation I'd tried to use it and faced

> Your requirements could not be resolved to an installable set of packages.

>  Problem 1
>    - Root composer.json requires anfischer/cloner ^0.1.0 -> satisfiable by anfischer/cloner[v0.1.0].
>    - anfischer/cloner v0.1.0 requires illuminate/support ^5.4.19 -> found illuminate/support[v5.4.19, ..., 5.8.x-dev] but it conflicts with another require.

## How has this been tested?

Ran the existing test suite on php 7.4.10 locally. ~~Pushing this will run it on Travis for me against two versions of PHP (7.3 and 7.4)~~ Travis isn't set up?

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Go over all the following points, and put an `x` in all the boxes that apply.

Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our [continuous integration](http://www.phptherightway.com/#continuous-integration) server to make sure your [tests and code style pass](https://help.github.com/articles/about-required-status-checks/).

- [x] I have read the **[CONTRIBUTING](CONTRIBUTING.md)** document.
- [x] My pull request addresses exactly one patch/feature.
- [x] I have created a branch for this patch/feature.
- [x] Each individual commit in the pull request is meaningful.
- [x] I have added tests to cover my changes.
- [x] If my change requires a change to the documentation, I have updated it accordingly.

If you're unsure about any of these, don't hesitate to ask. We're here to help!

Side note- why is composer.lock not committed?

### CODE REVIEW

**Comment by anfischer** [comment]
Hi Ben

Thanks for your contribution and sorry for my late response.

All looks good to me, could you please change the version number in the readme to v0.2 as you suggested? I concur with you as far as there is no need to bump to v1.0.0. Also, I agree with your suggestion to remove the null wrapper since it is available in the targeted laravel framework required by v0.2.

I have fixed the TravisCI integration for the repository and your PR passes (https://travis-ci.org/github/anfischer/cloner).

Let me know if you have the time to do the two changes/additions I suggested above and I will merge your PR.

Thanks again - I appreciate your work on this.

**Comment by benswinburne** [comment]
@anfischer I've made those changes.

I changed to Support\Collection as that is the one we're requiring in composer.json but previously, the NullWrapper had been importing Database\Eloquent\Collection...

Obviously it's not using any of the special Eloquent\Collection methods so it shouldn't matter (and tests pass).

That said, should `illuminate/database` perhaps be a dependency too given the use of it throughout the strategies etc?

Also, any particular reason you don't commit the lock file?

**Comment by anfischer** [comment]
@benswinburne Thank you!

I agree with you changing imports to Support\Collection, and I see no issue with making illuminate/database a required dependency.

Regarding the missing lock file I believe it to be due to an oversigt from me when I released the package initially, as it of course should be included in the repository. If you add requirements for illuminate/database could you commit your lock-file too? 

Thanks again for you putting time and work into the project.

**Comment by benswinburne** [comment]
I made a couple more changes to allow support more versions. Unfortunately I had to put the minimum php to 7.3 because of legacy-factories.

*If you wanted to a php7.1-7.2 L6-7 version we could remove 8 support from this PR, tag a release of cloner 0.2, then bump php ^7.3, L8 support w/ legacy factories and then tag cloner 0.3 in a second pr but this might be overkill- personally I think pushing people towards ^7.3 is probably a good idea*

Lock file - I haven't committed the lock file because I had a look at various other laravel packages and it seems more common to leave it out. Also, reading the composer docs suggests it makes no real difference https://getcomposer.org/doc/02-libraries.md#lock-file so I thought for the sake of making fewer changes I left it uncommitted.

**Comment by anfischer** [comment]
Thank you - I too consulted the composer docs based on your mention, and I see the point about not including the lock-file (it's great to learn something new every day).

Also regarding minimum required PHP-version: I agree with you and I definately think PHP 7.3 should be minimum required version as PHP 7.2 becomes EOL at the end of this month anyway.

I merged the PR and tagged release v0.2.0. Let me know if anything.

**Comment by benswinburne** [comment]
Fantastic, thanks very much!

**Pull request merged**
